Repository swciitg/resume-builder, pull requests merged in 2025-05, with the labels that each got.

#17 Main
  src/App.js
  src/Components/DisplayResume.js
  src/Components/LatexContext.js
  src/Components/Navbar.js
  src/Components/ResumeBuilder.js
  src/index.js
Labels: size:L

#18 UI update
  src/App.js
  src/Components/ResumeBuilder.js
  src/styles/resumeBuilder.css
Labels: size:XL

#19 latex fix
  backend/index.js
  backend/resume.out
  src/App.js
  src/Components/LatexCode.js
  src/Components/ResumeBuilder.js
Labels: size:M

#21 fixed addition function
  backend/index.js
  package-lock.json
  resume.out
  src/Components/DisplayResume.js
  src/Components/ResumeBuilder.js
  src/oldLatex.js
Labels: size:L

#22 instruction page
  backend/index.js
  src/App.js
  src/Components/DisplayResume.js
  src/Components/Instructions.js
Labels: size:L

#24 added logout button in navbar
  backend/index.js
  src/Components/Navbar.js
Labels: size:M

#27 footer
  resume.out
  src/App.js
  src/Components/Footer.js
  src/Components/Navbar.js
  src/Components/ResumeBuilder.js
  src/assets/Facebook.png
  src/assets/Instagram.png
  src/assets/LinkedIn.png
  src/assets/Twitter.png
  src/pages/ResumeBuilderPage.js
Labels: size:XXL

#28 landing page
  src/App.js
  src/Components/Footer.js
  src/assets/9.png
  src/assets/Outlook.png
  src/assets/Resume_sample.png
  src/assets/SWC.png
  src/assets/sample.png
  src/pages/LandingPage.js
  src/pages/ResumeBuilderPage.js
  tailwind.config.js
Labels: size:M

#29 landing page fix
  src/Components/Footer.js
  src/assets/Resume_sample.png
  src/assets/ellipse_1.png
  src/assets/resume_.png
  src/assets/tilted_resume.png
  src/pages/LandingPage.js
  tailwind.config.js
Labels: size:L
